### ISSUE TITLE
Bonfire Exact Change edge cases of concern?

### ISSUE THREAD

**Issue by bheavner** [Rafase282/My-FreeCodeCamp-Code#1]
There are cases where there is enough change in the drawer, but not enough _useful_ change. For example, if there's 1 $100 in the drawer, and you need $0.37 in change, you couldn't really make the change. Seems like it would be better to find the sum of useful change in drawer, rather than all change in drawer....

**Comment by Rafase282** [comment]
I haven't try that but it sound like it would be a good suggestion to the camp to implement a test for it.
