### ISSUE TITLE
Advanced scripting 3 - Exact Change 1 not working

### ISSUE THREAD

**Issue by ghost** [Rafase282/My-FreeCodeCamp-Code#12]
checkCashRegister(19.50, 20.00, [["PENNY", 0.01], ["NICKEL", 0], ["DIME", 0], ["QUARTER", 0], ["ONE", 1.00], ["FIVE", 0], ["TEN", 0], ["TWENTY", 0], ["ONE HUNDRED", 0]]) should return "Insufficient Funds".

This one is returning an incorrect array and not insufficient Funds

**Comment by Rafase282** [comment]
I haven't gone over this and I know there have been changes to the requirement. I will get to update it at some point but that will be for the code only no the wiki section.
