### ISSUE TITLE
Bonfire Truncate a string

### ISSUE THREAD

**Issue by CTenEyck219** [Rafase282/My-FreeCodeCamp-Code#14]
function truncate(str, num) {
    var truncd = '';
    if (str.length > num) {
        truncd = str.slice(0,num-3) + '...';
        return truncd;
    }
    return str;
}

does not accommodate 
truncateString("A-", 1) should return "A...".
truncateString("Absolutely Longer", 2) should return "Ab...".

Fix------

function truncateString(str, num) {
  var truncString = '';
   if (num < 3) {
    truncString = str.slice(0, num) + '...';
    return truncString;
  } 
  else if(str.length > num) {
    truncString = str.slice(0, num - 3) + '...';
    return truncString;
  }
  return str;
}

**Comment by Rafase282** [comment]
``` js
function truncateString(str, num) {
  if (str.length <= num) {
    return str;
  } else {
    return str.slice(0, num > 3 ? num - 3 : num) + '...';
  }
}

truncateString("A-tisket a-tasket A green and yellow basket", 11);
```

This is my current code, I do update them once in a while but only the code section.

**Comment by CTenEyck219** [comment]
Okay just making sure others knew. I like to compare my code to yours and see where I can improve on my codes readability and functionality. Thank you for the response!

**Comment by Rafase282** [comment]
Well I don't update mine as often because I have been updating and monitoring the answers I put on the FCC wiki.

**Comment by CTenEyck219** [comment]
Learn something new everyday, will have to check that out from now on then
