### ISSUE TITLE
Target the same element with multiple jQuery Selectors

### ISSUE THREAD

**Issue by Boneblivion** [Rafase282/My-FreeCodeCamp-Code#15]
The code you have adds three classes to #target1 when you're only supposed to only add one class with each of your three selectors. The last selector should add the class "btn-primary" to target one.

<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("btn-primary");
  });
</script>

**Comment by Rafase282** [comment]
Well if you are only supposed to add one class then do that, if anything the last one shows that you can add more than one class at the time so I see no reason to change it.
