### ISSUE TITLE
Intermediate Algorithm Scriptiing - 20 Bonfire Everything Be True.js

### ISSUE THREAD

**Issue by ariawanzero** [Rafase282/My-FreeCodeCamp-Code#18]
if (collection[c].hasOwnProperty(pre) || collection[c][pre] == pre) {
      counter++;
}

Hi I'm trying your code in my code camp
This condition give wrong result you can change with && and don't compare collection[c][pre] with pre but just collection[c][pre] so that become's correct
Thx for attention

**Comment by Rafase282** [comment]
Hello, it is possible that my solution is outdated as the challenges often change. Eventually I will get to it. That's why I do copy the challenge information .
