### ISSUE TITLE
Bonfire: Make a person

### ISSUE THREAD

**Issue by wake-0** [Rafase282/My-FreeCodeCamp-Code#2]
Hello Rafael,

i tried your code for the `Make a person` bonfire but it has not worked. I modified it to the following and it worked again. Please give me feedback.

```
var Person = function(firstAndLast) {

  var arr = firstAndLast.split(' ');

  this.getFirstName = function() {
    return arr[0];
  };

  this.getLastName = function() {
    return arr[1];
  };

  this.getFullName = function() {
    return arr[0] + " " + arr[1];
  };

  this.setFirstName = function(first) {
    arr[0] = first;
  };

  this.setLastName = function(last) {
    arr[1] = last;
  };

  this.setFullName = function(firstAndLast) {
    arr = firstAndLast.split(' ');
  };
};
```

**Comment by Rafase282** [comment]
Hello @Blackjack92 thanks for pointing that out. I haven't been checking the bonfires so I was not aware of the changes. FCC changes them from time to make minor adjustments which renders some of my old code obsolete. I had to solve the issue before looking at your code as the code here are supposed to be mine unless I paired with someone when solving them. However I did notice that it was mostly the same and your code works. I have already updated my solution.
