### ISSUE TITLE
Broken App Link for Voting App

### ISSUE THREAD

**Issue by AryanJ-NYC** [Rafase282/My-FreeCodeCamp-Code#20]
The [app link in the voting app Wiki](https://github.com/Rafase282/My-FreeCodeCamp-Code/wiki/Build-a-Voting-App#links) is broken.  I see it is linked to a [Cloud9](https://voting-app-rafase282.c9users.io/) workspace. They usually go down after a while. Heroku is probably a better option.

**Comment by Rafase282** [comment]
I don't think I actually finished that project. I normally go with heroku for the final project.
