### ISSUE TITLE
Challenge "Record Collection" Changed on FreeCodeCamp

### ISSUE THREAD

**Issue by wudifeixue** [Rafase282/My-FreeCodeCamp-Code#21]
Hi there, I was going through the questions on FCC and I realized that more restrictions has been put on the Challenge **Record Collection** than the one you have on [wiki](https://github.com/Rafase282/My-FreeCodeCamp-Code/wiki/Lesson-Review-Record-Collection).  

Since there is no current way I know to contribute to the wiki on Github, I will just post my working solution down below so you can update it on yours. 
## New Passing Solution

``` JavaScript
// Setup
var collection = {
    "2548": {
      "album": "Slippery When Wet",
      "artist": "Bon Jovi",
      "tracks": [ 
        "Let It Rock", 
        "You Give Love a Bad Name" 
      ]
    },
    "2468": {
      "album": "1999",
      "artist": "Prince",
      "tracks": [ 
        "1999", 
        "Little Red Corvette" 
      ]
    },
    "1245": {
      "artist": "Robert Palmer",
      "tracks": [ ]
    },
    "5439": {
      "album": "ABBA Gold"
    }
};
// Keep a copy of the collection for tests
var collectionCopy = JSON.parse(JSON.stringify(collection));

// Only change code below this line
function updateRecords(id, prop, value) {
  if (value === "") {
    delete collection[id][prop];
  }

  else if (prop !== "tracks") {
    collection[id][prop] = value;
  }

  else if (!collection[id].hasOwnProperty("tracks")) {
    collection[id][prop] = [];
    collection[id][prop].push(value);
  }

  else {
    collection[id][prop].push(value);
  }

  return collection;
}

// Alter values below to test your code
updateRecords(5439, "artist", "ABBA");


```

**Comment by Rafase282** [comment]
If you are trying to have the solution on my repo then I have to say that I'm not accepting code solutions, but if you are looking for the FCC wiki then it was moved to the forum.

**Comment by wudifeixue** [comment]
Hi sorry that I probably should not post the solutions out, I read that you have mentioned if the challenge is updated you would update your solution too, so basically just want to let you know this challenge is updated. Any thank you for letting me know the wiki was moved to the forum. 👍
