### ISSUE TITLE
Lesson-Review-Counting-Cards

### ISSUE THREAD

**Issue by As3toJs** [Rafase282/My-FreeCodeCamp-Code#27]
This condition getting failed on execution:
Cards Sequence 2, J, 9, 2, 7 should return "1 Bet"

**Comment by Rafase282** [comment]
Is that based on the current guidelines on freeCodeCamp or the ones mentioned here?

**Comment by As3toJs** [comment]
I created the issue because either "Lesson review is wrong" or condition which needs to be satisfied is wrong. I tried with the code (exact same as Lesson review) but given condition is still not true. There is something wrong. 

Let me know if it's not a right place to mention this issue.

**Comment by Rafase282** [comment]
The code is based on an earlier version so if you copy and paste it on freeCodeCamp, it will not work.

**Comment by As3toJs** [comment]
got it :)
