### ISSUE TITLE
understanding case sensitive in variable

### ISSUE THREAD

**Issue by hasmukhgagal** [Rafase282/My-FreeCodeCamp-Code#28]
`<script>
  $(document).ready(function() {

 
  $("button").addclass("animated bounce");
    
  });
</script>
`
it's not working.

**Comment by Rafase282** [comment]
It should work. What problem are you getting?

**Comment by hasmukhgagal** [comment]
Use the jQuery addClass() function to give the classes animated and bounce to  button elements.
it should not work

**Comment by Rafase282** [comment]
Could you point the file where that is. I already see the problem.

**Comment by hasmukhgagal** [comment]
![2017-03-29-080815_1024x768_scrot](https://cloud.githubusercontent.com/assets/26369385/24436511/919df084-1459-11e7-82dd-bf8d1ec41d42.png)

**Comment by hasmukhgagal** [comment]
![2017-03-29-080815_1024x768_scrot](https://cloud.githubusercontent.com/assets/26369385/24436534/aafe3584-1459-11e7-8825-1580d4a979cf.png)

**Comment by Rafase282** [comment]
Looks like you found your mistake. It is `addClass` not `addclass`.

**Comment by hasmukhgagal** [comment]
thats my code.

**Comment by Rafase282** [comment]
See my previous comment, you have to pay attention to the function names, they are case sensitive.

**Comment by hasmukhgagal** [comment]
thanks for give me a guide.

that is a small problem but i did not saw it.

thanks

**Comment by hasmukhgagal** [comment]
// Declarations
var StUdLyCapVaR;
var properCamelCase;
var TitleCaseOver;

// Assignments
STUDLYCAPVAR = 10;
PRoperCAmelCAse = "A String";
tITLEcASEoVER = 9000;


var studlyCapVar;
var properCamelCase;
var titleCaseOver;


studlyCapVar = 10;
properCamelCase = "A String";
titleCaseOver = 9000;


here is error with  properCamelCase.

 properCamelCase should use camelCase in both declaration and assignment sections.
has an issue

please help
