### ISSUE TITLE
Bonfire Diff Two Arrays Solution is incorrect

### ISSUE THREAD

**Issue by abhinavagrawal1995** [Rafase282/My-FreeCodeCamp-Code#29]

**Comment by Rafase282** [comment]
Care to elaborate?

**Comment by abhinavagrawal1995** [comment]
Tried the exact code on FreeCodeCamp site. Worked for 4 test cases and failed for others.

**Comment by Rafase282** [comment]
Then that means freeCodeCamp changed their requirements. I have the old ones here. If you understands the solutions then it wont be an issue to finish it over on FCC.
