### ISSUE TITLE
jQuery Lesson 6

### ISSUE THREAD

**Issue by ajoshi2733** [Rafase282/My-FreeCodeCamp-Code#31]
<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("animated shake  #btn-primary");
  });
</script>

In the above code, you should be targeting one element by adding one class at a time. 
Correction should be $("#target1").addClass("btn-primary")

Thanks for the great work bro!!

**Comment by Rafase282** [comment]
```html
<script>
  $(document).ready(function() {
    $("button").addClass("animated");
    $(".btn").addClass("shake");
    $("#target1").addClass("animated shake btn-primary");
  });
</script>
```

But yes, you should do the last one one by one as per the current instructions on freeCodeCamp.
With that said, where did you see that `btn-primary` had an `#` in my code?

Outside of fCC there is no reason or value to add them one by one, if anything this example already shows how to do it one by one and multiple at the same time.
