### ISSUE TITLE
Geolocation does not work (edit)

### ISSUE THREAD

**Issue by chrisjim316** [Rafase282/My-FreeCodeCamp-Code#33]
## In Local Weather App (intermediate front-end project), 
Custom background does not change base on weather conditions.

**Code below is flawed: (calling an array of images on the jQuery function will not be successful)** 
 getWeather = function(data) {
     // other code in between.
    // Array of backgroudn images.
    var imgs = ['url("http://i.imgur.com/eI5KLUW.jpg")',
      'url("http://i.imgur.com/rG0P1ro.jpg")', 'url("http://i.imgur.com/voCuONs.jpg")',
      'url("http://i.imgur.com/5tFHSKa.jpg")',
    ];

    // Select custom backgroudn image according to temperature range.
    if (temp >= temps[0]) {
      $('body').css('background-image', imgs[0]);
    } else if (temp < temps[0] && temp >= temps[1]) {
      $('body').css('background-image', imgs[1]);
    } else if (temp < temps[1] && temp >= temps[2]) {
      $('body').css('background-image', imgs[2]);
    } else if (temp < temps[2]) {
      $('body').css('background-image', imgs[3]);
    }
  };

**Correct version:** (sample) 
$("body").css("background-image", "url(https://github.com/chrisjim316/freeCodeCamp-/blob/master/09-Intermediate-FE-Projects/Local%20Weather%20App/Images/backgroundChanging/thunderstorm.jpg?raw=true)");

**Comment by pilarmireles22** [comment]
share me your codepen for seeing it.

**Comment by chrisjim316** [comment]
this is my random quote generator just for demonstration purposes because it changes background based on the quote of the author. 
Same technique used in the local weather app. 

https://codepen.io/liljimbos/full/JydZJX/

**Comment by Rafase282** [comment]
I'm not sure what you are implying. The script does work and the background image changes according to the temp. While using https requires you to "load unsafe" scripts the app does have this functionality working.

**Comment by chrisjim316** [comment]
I tried using an array of imgs like you did, but it wouldn't allow me to change background images. Maybe you import different versions of jQuery? I'm not so sure, but this problem is solved nonetheless.

Additionally, I would like to ask for help...
Even though my browser(iPhone Safari) supports geolocation ( tested my local weather app's geolocation API), your live demo doesn't work on mine. This has bugged me for a little while now because my app doesn't work on some Android phones either.  
Do you have any idea why or how to fix it? I confirmed that it wasn't http vs https problem.

**Comment by Rafase282** [comment]
Not sure, I didn't know mine doesnt work on safari. Could be browser specific API although if I remember correctly, I used the html5 one. I would say see if you can find one that is more reliable even if it is not a built in one.
