### ISSUE TITLE
[General Question] Program you used for drawings

### ISSUE THREAD

**Issue by bauerjj** [Rafase282/My-FreeCodeCamp-Code#34]
Just a general question - What is the program you used to produce the hand-drawn looking images? Thanks

**Comment by Rafase282** [comment]
Which images are those?

**Comment by bauerjj** [comment]
From this page: https://github.com/Rafase282/My-FreeCodeCamp-Code/wiki/Lesson-Save-your-Code-Revisions-Forever-with-Git

Here is a direct link to one of the images: 

https://camo.githubusercontent.com/d4de2fdb747fec0d3dc67b1640f37c12f3786f5b/687474703a2f2f6a6c6f72642e75732f6769742d69742f6173736574732f696d67732f72656d6f7465732e706e67

**Comment by Rafase282** [comment]
Oh, I didn't make those, just used them.

**Comment by bauerjj** [comment]
where did you get them from..? Tinyeye is returning 0 matches

**Comment by Rafase282** [comment]
From the very first line ...

`All the material was directly obtained from this page: http://jlord.us/git-it/index.html`
