### ISSUE TITLE
Chaining If Else statements

### ISSUE THREAD

**Issue by ChloeB123** [Rafase282/My-FreeCodeCamp-Code#36]
Hello,

I'm pretty sure my code is correct but For the Chaining If Else Statements lesson, it won't acknowledge that it's correct so I can't proceed:

![capture 07](https://user-images.githubusercontent.com/23516061/29895673-db40375c-8d8e-11e7-829d-a98c232ae90e.JPG)

**Comment by DeysiR** [comment]
Hi Cloe

Looks like you have Capital letters and some are small. Make sure you start with the same in all of them in this case Capital letters.
The code is quite sensitive so you need to be careful with that.

Best of lucks
Deysi

Sent from my iPhone

On 30 Aug 2017, at 22:24, Chloe <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I'm pretty sure my code is correct but For the Chaining If Else Statements lesson, it won't acknowledge that it's correct so I can't proceed:

[capture 07]<https://user-images.githubusercontent.com/23516061/29895673-db40375c-8d8e-11e7-829d-a98c232ae90e.JPG>

**Comment by ChloeB123** [comment]
It worked! Thank you!

**Comment by DeysiR** [comment]
You Welcome :)


________________________________
De: Chloe <notifications@github.com>
Enviado: 31 de agosto de 2017 00:49
Para: Rafase282/My-FreeCodeCamp-Code
Cc: DeysiR; Comment
Assunto: Re: [Rafase282/My-FreeCodeCamp-Code] Chaining If Else statements (#36)


It worked! Thank you!
