### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by profoundhub** [Rafase282/My-FreeCodeCamp-Code#37]
Broken Link found in the Wiki: https://github.com/Rafase282/My-FreeCodeCamp-Code/wiki/URL-Shortener-Microservice

... revisit http://freecodecamp.com/challenges/get-set-for-basejumps. 

I believe the link has been changed to: https://www.freecodecamp.org/challenges/get-set-for-our-api-development-projects

**Comment by Rafase282** [comment]
Thank for letting me know. I have updated the link.
