### ISSUE TITLE
Outdated solution.

### ISSUE THREAD

**Issue by mrkaluzny** [Rafase282/My-FreeCodeCamp-Code#5]
Hi!

The code you proposed doesn't work that well ;) My final version below:

`function checkCashRegister(price, cash, cid) {
  var totalChange = +(cash - price).toFixed(2);
  var stdCurr = [0.01, 0.05, 0.10, 0.25, 1, 5, 10, 20, 100];
  var currType;
  var stdCurrAmount;
  var currCurrency;
  var changeArr = [];
  var totalCash = +cid.map(function(money) {
    return money[1];
  }).reduce(function(cash1, cash2) {
    return cash1 + cash2;
  }).toFixed(2);

  var resultAmount = 0;

  function check(result) {
    for (var i = 0; i < result.length; i++){
      resultAmount += result[i][1];
    }

```
if (resultAmount < totalChange) {
  return false;
} else {
  return true;
}
```

  }

  if (totalChange > totalCash) {
    return 'Insufficient Funds';
  } else if (totalChange === totalCash) {
    return 'Closed';
  }

  for (var i = +cid.length - 1; i >= 0; i--) {
    currCurrency = +cid[i][1].toFixed(2);
    currType = cid[i][0];

```
if (+stdCurr[i].toFixed(2) <= +totalChange.toFixed(2)) {

  stdCurrAmount = Math.floor(currCurrency / stdCurr[i]);

  if ((stdCurr[i] * stdCurrAmount) >= totalChange) {
    stdCurrAmount = Math.floor(totalChange / stdCurr[i]);
  }

  currCurrency = +(stdCurr[i] * stdCurrAmount).toFixed(2);
  totalChange = +(totalChange - currCurrency).toFixed(2);

  cid[i][1] = currCurrency;
  changeArr.push([currType, currCurrency]);
}
```

  }

  if (check(changeArr) === false){
    return 'Insufficient Funds';
  } else {
    return changeArr;
  }

}`

**Comment by Rafase282** [comment]
I'm going over the challenges again and updating the code side so eventually I'll get to this one.
