### ISSUE TITLE
"Ans" button in freeCodeCamp's JavaScript Calculator example not functional

### ISSUE THREAD

**Issue by LeWood16** [Rafase282/My-FreeCodeCamp-Code#8]
This challenge was a lot of fun! I'm not sure whether someone had already pointed this issue out (I couldn't find someone else posting about it anywhere), but the button in the example program that stores the last answer to be used later (the "ANS" button) doesn't do anything; For example when you type "2+2=", 4 appears, then when you type "Ans+2=" you simply get 2, meaning it starts from 0 again, and nothing seems to be stored for later use.

I'm not sure if this would be considered a bug or not but I thought it was odd to have a button that doesn't do anything.

Here is the link to my code if it's any help: https://codepen.io/LeFonze/pen/pbzYGo

**Comment by Rafase282** [comment]
Honestly I don't even remember coding that, or even using it on physical calculators.

**Comment by Rafase282** [comment]
I'll set some time aside to go over my material and fix/update everything I find.

**Comment by LeWood16** [comment]
Whoops sorry I thought I was posting to freecodecamp's page for their example; I'm still kind of new at this. I was looking for their wiki on the calculator challenge and yours came up first

**Comment by LeWood16** [comment]
I saw yours and it didn't have the ANS button anyway, so it's not really an issue.  Just the button on FCC's that didn't do anything bugged me is all.

**Comment by LeWood16** [comment]
Found the right repository, I just submitted it there instead.
